version: '3'

services:
  chatbot:
    build: .
    ports:
      - "8501:8501"
    environment:
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - WS_ENDPOINT=${WS_ENDPOINT}
      - API_KEY=${API_KEY}
      - DEBUG=${DEBUG:-False}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - .:/app 